# Generated by Django 6.1 on 2026-09-05 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('EXPENSE', 'Expense'), ('CUSTOMER', 'Customer'), ('PRODUCT', 'Product')], max_length=20)),
                ('source', models.CharField(choices=[('RULE', 'Business rule'), ('STAT', 'Statistical analysis'), ('ML', 'Machine learning'), ('AI', 'AI interpretation')], default='RULE', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('observation', models.TextField(help_text='What the data shows')),
                ('interpretation', models.TextField(blank=True, help_text='AI-generated meaning')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='businesses.business')),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to='businesses.business')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('suggestion', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('DISMISSED', 'Dismissed'), ('DONE', 'Done')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='businesses.business')),
                ('related_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='ai_engine.aiinsight')),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(default='sales', max_length=50)),
                ('horizon_days', models.PositiveIntegerField(default=7)),
                ('model_name', models.CharField(max_length=80)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('series', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='businesses.business')),
            ],
            options={
                'db_table': 'ai_forecast_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
