# Generated by Django 6.1 on 2026-09-05 10:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='confidence',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='insight_kind',
            field=models.CharField(default='insight', max_length=30),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='related_entity_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='severity_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='source_model',
            field=models.CharField(default='rules.v1', max_length=80),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AIInsightFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DISMISSED', 'Dismissed'), ('EDITED', 'Edited')], max_length=12)),
                ('model_version', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='businesses.business')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_engine.aiinsight')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_insight_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'action', 'created_at'], name='ai_insight__busines_26e23f_idx'), models.Index(fields=['insight', 'created_at'], name='ai_insight__insight_6efe2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feature_date', models.DateField()),
                ('features', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feature_snapshots', to='businesses.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_feature_snapshots', to='products.product')),
            ],
            options={
                'db_table': 'ai_feature_snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['business', 'feature_date'], name='ai_feature__busines_9e2adf_idx'), models.Index(fields=['business', 'product', 'feature_date'], name='ai_feature__busines_e6631c_idx')],
            },
        ),
    ]
