# Generated by Django 6.1 on 2026-09-05 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aiinsight_confidence_aiinsight_dedupe_key_and_more'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='delivery_band',
            field=models.CharField(default='background', max_length=20),
        ),
        migrations.CreateModel(
            name='InsightDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_deliveries', to='businesses.business')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ai_engine.aiinsight')),
            ],
            options={
                'db_table': 'ai_insight_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'channel', 'created_at'], name='ai_insight__busines_cc18e8_idx'), models.Index(fields=['insight', 'channel'], name='ai_insight__insight_70df40_idx')],
            },
        ),
    ]
