# Generated by Django 6.1 on 2026-10-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_aiinsight_delivery_band_insightdelivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIQuery',
        ),
    ]
