# Generated by Django 6.1 on 2026-10-01 12:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_business_barber_type'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0002_barber_sale_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('IN_SERVICE', 'In service'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=12)),
                ('source', models.CharField(choices=[('PHONE', 'Phone'), ('WALK_IN', 'Walk-in'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], default='PHONE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_appointments', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_appointments', to='customers.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_appointments', to='sales.sale')),
                ('services', models.ManyToManyField(related_name='salon_appointments', to='products.product')),
                ('stylist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'created_at'],
                'indexes': [models.Index(fields=['business', 'starts_at', 'status'], name='salon_salon_busines_b0613c_idx'), models.Index(fields=['business', 'stylist', 'starts_at'], name='salon_salon_busines_1d4a80_idx')],
            },
        ),
    ]
