# Generated by Django 6.1 on 2026-10-01 13:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_barber_type'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0002_barber_sale_fields'),
        ('salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonClientPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('sessions_total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sessions_redeemed', models.PositiveSmallIntegerField(default=0)),
                ('purchased_at', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_client_packages', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_packages_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salon_packages', to='customers.customer')),
                ('purchase_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_client_packages', to='sales.sale')),
                ('services', models.ManyToManyField(related_name='salon_client_packages', to='products.product')),
            ],
            options={
                'ordering': ['-purchased_at', 'customer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalonPackageRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_redemptions', to='salon.salonappointment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_package_redemptions', to='businesses.business')),
                ('client_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='salon.salonclientpackage')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_package_redemptions', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salon_package_redemptions', to='products.product')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salonclientpackage',
            index=models.Index(fields=['business', 'customer', 'expires_at'], name='salon_salon_busines_ec808a_idx'),
        ),
        migrations.AddConstraint(
            model_name='salonclientpackage',
            constraint=models.CheckConstraint(condition=models.Q(('sessions_redeemed__lte', models.F('sessions_total'))), name='salon_package_redemptions_lte_total'),
        ),
        migrations.AddIndex(
            model_name='salonpackageredemption',
            index=models.Index(fields=['business', 'redeemed_at'], name='salon_salon_busines_083de6_idx'),
        ),
        migrations.AddConstraint(
            model_name='salonpackageredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('client_package', 'appointment'), name='uniq_salon_package_per_appointment'),
        ),
    ]
