# Generated by Django 6.1 on 2026-09-05 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('KPI', 'KPI Card'), ('CHART', 'Chart'), ('TABLE', 'Table'), ('LIST', 'List'), ('INSIGHT', 'Insight'), ('ALERT', 'Alert')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('LINE', 'Line Chart'), ('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('DOUGHNUT', 'Doughnut Chart'), ('AREA', 'Area Chart'), ('STACKED_BAR', 'Stacked Bar')], max_length=20, null=True)),
                ('data_source', models.CharField(max_length=100)),
                ('metric', models.CharField(max_length=100)),
                ('aggregation', models.CharField(default='SUM', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=2)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=300, help_text='Refresh interval in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='businesses.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_widgets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'db_table': 'analytics_dashboard_widget',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('PDF', 'PDF Report'), ('CSV', 'CSV Data'), ('EXCEL', 'Excel Spreadsheet'), ('JSON', 'JSON Data')], max_length=20)),
                ('module', models.CharField(choices=[('SALES', 'Sales'), ('PRODUCTS', 'Products'), ('INVENTORY', 'Inventory'), ('CUSTOMERS', 'Customers'), ('EXPENSES', 'Expenses'), ('FINANCIAL', 'Financial')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('date_range', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'db_table': 'analytics_export_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('TREND', 'Trend Detected'), ('ANOMALY', 'Anomaly Detected'), ('OPPORTUNITY', 'Opportunity'), ('RISK', 'Risk Identified'), ('RECOMMENDATION', 'Recommendation'), ('FORECAST', 'Forecast')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('SUCCESS', 'Success')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('metric', models.CharField(blank=True, max_length=100)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('time_period', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Insight',
                'verbose_name_plural': 'Business Insights',
                'db_table': 'analytics_business_insight',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['business', 'generated_at'], name='analytics_b_busines_476244_idx'), models.Index(fields=['business', 'insight_type'], name='analytics_b_busines_d7d3da_idx'), models.Index(fields=['business', 'severity'], name='analytics_b_busines_e1b174_idx'), models.Index(fields=['business', 'is_read'], name='analytics_b_busines_b00d31_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('SALES_COUNT', 'Sales Count'), ('EXPENSES', 'Expenses'), ('PROFIT', 'Profit'), ('CUSTOMERS', 'Customers'), ('PRODUCTS_SOLD', 'Products Sold'), ('INVENTORY_VALUE', 'Inventory Value'), ('AVERAGE_ORDER_VALUE', 'Average Order Value'), ('CUSTOMER_RETENTION', 'Customer Retention')], max_length=30)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Metric',
                'verbose_name_plural': 'Business Metrics',
                'db_table': 'analytics_business_metric',
                'indexes': [models.Index(fields=['business', 'metric_type', 'date'], name='analytics_b_busines_d53b03_idx'), models.Index(fields=['business', 'date'], name='analytics_b_busines_f95663_idx')],
                'unique_together': {('business', 'metric_type', 'date')},
            },
        ),
    ]
