# Generated by Django 6.1 on 2026-09-05 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail Shop'), ('RESTAURANT', 'Restaurant'), ('SALON', 'Salon/Barbershop'), ('WHOLESALE', 'Wholesale'), ('SERVICE', 'Service Business'), ('ELECTRONICS', 'Electronics Shop'), ('BOUTIQUE', 'Boutique'), ('HARDWARE', 'Hardware Shop'), ('FREELANCE', 'Freelance/Agency'), ('OTHER', 'Other')], default='RETAIL', max_length=20)),
                ('business_size', models.CharField(choices=[('MICRO', 'Micro (1-5 employees)'), ('SMALL', 'Small (6-20 employees)'), ('MEDIUM', 'Medium (21-50 employees)')], default='MICRO', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('color_theme', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('fiscal_year_start', models.DateField(default=django.utils.timezone.now)),
                ('inventory_valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('AVERAGE', 'Average Cost')], default='FIFO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic SME'), ('SMART', 'SmartBiz AI'), ('PRO', 'Business/Professional')], default='FREE', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses_business',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Branch',
                'verbose_name_plural': 'Business Branches',
                'db_table': 'businesses_branch',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('invoice_footer', models.TextField(blank=True, help_text='Footer text on invoices')),
                ('invoice_tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('invoice_terms', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('show_stock_on_receipt', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('alert_low_stock', models.BooleanField(default=True)),
                ('alert_daily_summary', models.BooleanField(default=True)),
                ('alert_weekly_summary', models.BooleanField(default=True)),
                ('tax_enabled', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=True)),
                ('email_sender', models.EmailField(blank=True, max_length=254)),
                ('email_subject_prefix', models.CharField(default='SmartBiz AI - ', max_length=50)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(blank=True, max_length=50)),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Business Setting',
                'verbose_name_plural': 'Business Settings',
                'db_table': 'businesses_settings',
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='businesses__name_a138ad_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type'], name='businesses__busines_cfa4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['subscription_tier'], name='businesses__subscri_32130f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active'], name='businesses__is_acti_e70536_idx'),
        ),
    ]
