# Generated by Django 6.1 on 2026-09-05 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('count_date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('expected_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Expected value based on system records', max_digits=12)),
                ('actual_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual value from physical count', max_digits=12)),
                ('difference_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_approved', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='businesses.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Count',
                'verbose_name_plural': 'Stock Counts',
                'db_table': 'inventory_stock_count',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('counted_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('difference', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expected_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('counted_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('difference_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_items', to='products.product')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
            ],
            options={
                'verbose_name': 'Stock Count Item',
                'verbose_name_plural': 'Stock Count Items',
                'db_table': 'inventory_stock_count_item',
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('EXPIRY', 'Expiry Date'), ('SLOW_MOVING', 'Slow Moving'), ('OVERSTOCKED', 'Overstocked')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('message', models.TextField()),
                ('current_value', models.FloatField(default=0)),
                ('threshold_value', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('IGNORED', 'Ignored')], default='ACTIVE', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='products.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Alert',
                'verbose_name_plural': 'Inventory Alerts',
                'db_table': 'inventory_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='inventory_a_busines_ecae10_idx'), models.Index(fields=['business', 'alert_type'], name='inventory_a_busines_c5caca_idx'), models.Index(fields=['business', 'severity'], name='inventory_a_busines_d4a083_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('WASTE', 'Waste/Damage'), ('RECEIVED', 'Received from Supplier'), ('RETURNED_TO_SUPPLIER', 'Returned to Supplier'), ('INITIAL', 'Initial Stock'), ('COUNT', 'Stock Count')], max_length=25)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('previous_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='businesses.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'db_table': 'inventory_transaction',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['business', 'transaction_date'], name='inventory_t_busines_ce6d44_idx'), models.Index(fields=['business', 'product'], name='inventory_t_busines_263950_idx'), models.Index(fields=['business', 'transaction_type'], name='inventory_t_busines_5f6a4d_idx'), models.Index(fields=['business', 'reference_number'], name='inventory_t_busines_47c42f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['business', 'count_date'], name='inventory_s_busines_5fba61_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['business', 'status'], name='inventory_s_busines_830994_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountitem',
            unique_together={('stock_count', 'product')},
        ),
    ]
