# Generated by Django 6.1 on 2026-10-02 19:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_business_barber_type'),
        ('products', '0001_initial'),
        ('sales', '0002_barber_sale_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('COOKING', 'Cooking'), ('READY', 'Ready'), ('COLLECTED', 'Collected')], db_index=True, default='NEW', max_length=12)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket', to='sales.sale')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantCashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cash_shifts', to='businesses.business')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_shifts_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantCashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Cash in'), ('OUT', 'Cash out')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='restaurant.restaurantcashshift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=0)),
                ('method', models.TextField(blank=True)),
                ('yield_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(100)])),
                ('waste_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.99)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_recipe', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_recipe_usages', to='products.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.restaurantrecipe')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_suppliers', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('zone', models.CharField(default='Indoor', max_length=80)),
                ('seats', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('BILL_REQUESTED', 'Bill requested'), ('NEEDS_ATTENTION', 'Needs attention'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
                ('position_x', models.PositiveSmallIntegerField(default=0)),
                ('position_y', models.PositiveSmallIntegerField(default=0)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tables', to='businesses.business')),
            ],
            options={
                'ordering': ['zone', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=24, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('party_size', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reservations', to='businesses.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='restaurant.restauranttable')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurantcashshift',
            index=models.Index(fields=['business', 'closed_at'], name='restaurant__busines_ffe2d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurantrecipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='uniq_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='restaurantsupplier',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='uniq_restaurant_supplier_name'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='uniq_restaurant_table_number'),
        ),
        migrations.AddIndex(
            model_name='restaurantreservation',
            index=models.Index(fields=['business', 'starts_at', 'status'], name='restaurant__busines_2b391c_idx'),
        ),
    ]
