# Generated by Django 6.1 on 2026-10-02 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_barber_type'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurantcashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('business',), name='uniq_open_restaurant_cash_shift'),
        ),
    ]
