# Generated by Django 6.1 on 2026-10-01 06:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
        ('businesses', '0003_business_barber_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('DAILY_REVENUE', 'Daily revenue'), ('WEEKLY_CUTS', 'Weekly cuts'), ('MONTHLY_CLIENTS', 'Monthly new clients'), ('MONTHLY_REVENUE', 'Monthly revenue')], max_length=24)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarberShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_day_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shift_date', 'chair__label', 'start_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='barber_appo_busines_6919e3_idx',
            old_name='barber_appoint_business_4a8f51_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='barber_appo_barber__4ceedd_idx',
            old_name='barber_appoint_barber_23492c_idx',
        ),
        migrations.AddField(
            model_name='barbergoal',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_goals', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='barbershift',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_barber_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barbershift',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_shifts', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='barbershift',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='barber.chair'),
        ),
        migrations.AddIndex(
            model_name='barbershift',
            index=models.Index(fields=['business', 'shift_date'], name='barber_barb_busines_1c0f3d_idx'),
        ),
    ]
