# Generated by Django 6.1 on 2026-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_barbergoal_barbershift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbergoal',
            name='metric',
            field=models.CharField(choices=[('DAILY_REVENUE', 'Daily revenue'), ('WEEKLY_CUTS', 'Weekly cuts'), ('MONTHLY_CLIENTS', 'Monthly new clients'), ('MONTHLY_REVENUE', 'Monthly revenue'), ('MONTHLY_ATTACH_RATE', 'Monthly product attach rate'), ('MONTHLY_REPEAT_RATE', 'Monthly repeat client rate')], max_length=24),
        ),
    ]
